Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "matrix" do |vpn|
     vpn.vm.hostname = "matrix"
     vpn.vm.network "private_network", ip: "192.168.77.220"
     vpn.vm.provision :ansible do |ansible|
       ansible.limit = "all"
     #  ansible.inventory_path = "test/hosts/vagrant"
       ansible.playbook = "main.yml"
    end
  end
end
