Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "matrix" do |vpn|
     vpn.vm.hostname = "matrix"
     vpn.vm.network "public_network", dev: "wlp4s0:", bridge: "wlp4s0:"
     vpn.vm.provision :ansible do |ansible|
       ansible.limit = "all"
     #  ansible.inventory_path = "test/hosts/vagrant"
       ansible.playbook = "../main.yml"
    end
  end
end
