---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
          - include: tasks/repo.yml
          - include: tasks/install.yml
          - include: tasks/configure.yml
                  #- tasks/encrypt.yml
                  #- tasks/web.yml
