---

- name: Server name config
  template: 
    src: templates/server_name.yaml.j2
    dest: /etc/matrix-synapse/conf.d/server_name.yaml
    mode: 0644

- name: Server log report config
  template: 
    src: templates/report_stats.yaml.j2
    dest: /etc/matrix-synapse/conf.d/report_stats.yaml
    mode: 0644

- name: Server log homeserver config
  template: 
    src: templates/homeserver.yaml.j2
    dest: /etc/matrix-synapse/homeserver.yaml
    mode: 0644

- name: setting ownership on homeserver.db
  file:
    state: touch
    path: /var/lib/matrix-synapse/homeserver.db
    owner: matrix-synapse

- name: ensure matrix-synapse is running (and enable it at boot)
  service: name=matrix-synapse state=restarted enabled=yes
