---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

driver:
  name: docker

platforms:
  - name: synapse-docker-host
    image: geerlingguy/docker-debian12-ansible@sha256:3232ce7d506146b149802b561f49871dde8339fa6cb0e175c69db69530cedd47 # yamllint disable-line rule:line-length
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  inventory:
    host_vars:
      synapse-docker-host:
        synapse_server_name: test.matrix.local
        synapse_deployment_mode: docker
        synapse_database_engine: postgresql
        synapse_database_password: synapse-test-password
        synapse_tls_mode: none
        synapse_registration_shared_secret: test-secret-change-me
        synapse_create_admin: false

verifier:
  name: ansible
