---
- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
      - python3-docker
    state: present
    update_cache: true

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
